KanaPen24/414Game

414Game/Assets/Personal/Kanase/Prehub.meta
414Game/Assets/Personal/Kanase/Prehub/Canvas.prefab
414Game/Assets/Personal/Kanase/Prehub/Canvas.prefab.meta
414Game/Assets/Personal/Kanase/Scene/ProtoKanase.unity
414Game/Assets/Script/System/FpsDisplay.cs
414Game/Logs/AssetImportWorker0-prev.log
414Game/Logs/AssetImportWorker1-prev.log
414Game/Logs/AssetImportWorker1.log
414Game/Logs/shadercompiler-UnityShaderCompiler.exe0.log
414Game/UserSettings/Layouts/default-2021.dwlt
414Game/obj/Debug/Assembly-CSharp.csproj.CoreCompileInputs.cache

Create prehub canvas
Change FPS font

Create prehub canvas

---

414Game/Assets/Personal/Ihara/Script/Player/IS_Player.cs
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Scene/ProtoKanase.unity
414Game/Assets/Personal/Kanase/Script/YK_HPBerHP.cs
414Game/Assets/Personal/Kanase/Script/YK_PlayerHP.cs
414Game/ProjectSettings/InputManager.asset

Controller compatible&Change ProjectSetting

Controller compatible

---

414Game/Assets/Live2D/Cubism/Samples/Models/Mao/Mao.fadeMotionList.asset
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/mtn_01.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/mtn_02.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/mtn_03.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/mtn_04.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/special_01.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Mao/motions/special_02.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/Natori.fadeMotionList.asset
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_00.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_01.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_02.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_03.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_04.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_05.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_06.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_07.anim
414Game/Assets/Live2D/Cubism/Samples/Models/Natori/motions/mtn_08.anim
414Game/Assets/Personal/Ikezaki/Effect/E_Vortex.prefab
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Scene/ProtoKanase.unity
414Game/Assets/Personal/Kanase/Script/YK_HPBar.cs
414Game/Assets/Personal/Kanase/Script/YK_HPBarVisible.cs
414Game/Assets/Personal/Kanase/Script/YK_SkillIcon.cs
414Game/Assets/Personal/Kanase/Script/YK_UI.cs
414Game/Assets/Personal/Kanase/Script/YK_UICatcher.cs
414Game/UserSettings/Layouts/CurrentMaximizeLayout.dwlt

Fix UICatcher

---

414Game/Assets/Personal/Ihara/Prefab/GameSceneCamera.prefab
414Game/Assets/Personal/Ihara/Prefab/GameSceneCamera.prefab.meta
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab

GameSceneのカメラPrefab,
YK_CanvasのsortinglayerをCanvasに変更

GameScene更新

---

414Game/Assets/Personal/Osaki/Material/ON_Mat_Mountain.mat
414Game/Assets/Personal/Osaki/Material/ON_Mat_Sky.mat
414Game/Assets/Personal/Osaki/Prefab/ON_BackGround_1.prefab
414Game/Assets/Personal/Osaki/Scene/ON_StageTest.unity
414Game/Assets/Personal/Osaki/Texture/Stage/背景_前.png.meta
414Game/Assets/Personal/Osaki/Texture/Stage/背景_奥01.png.meta
414Game/Assets/Personal/Osaki/Texture/Stage/背景_奥02.png.meta
414Game/Assets/Personal/Osaki/Texture/Stage/背景_奥03.png.meta
414Game/Assets/Personal/Osaki/Texture/Stage/背景_最奥.png.meta

シェーダー使用時の画像のチラツキ修正

---

414Game/Assets/Fade/Materials/UI-Fade-Cutout.mat
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_SkillIcon.cs
414Game/Assets/Personal/Kanase/UI/YK_Icon.png.meta

fix canvas

---

414Game/Assets/Fade/Materials/UI-Fade-Cutout.mat
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab

fix Canvasprefub

---

414Game/Assets/Personal/Ihara/Prefab/IS_GameManager.prefab
414Game/Assets/Personal/Kanase/Script/YK_GameOver.cs

Add GameOver

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_BossHP.cs
414Game/Assets/Personal/Kanase/Script/YK_Clock.cs
414Game/Assets/Personal/Kanase/Script/YK_HPBar.cs
414Game/Assets/Personal/Kanase/Script/YK_MoveCursol.cs
414Game/Assets/Personal/Kanase/Script/YK_Next.cs
414Game/Assets/Personal/Kanase/Script/YK_SkillIcon.cs

Add Comment

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_MoveCursol.cs

Fix Cursol

---

414Game/Assets/Fade/Materials/UI-Fade-Cutout.mat
414Game/Assets/Personal/Osaki/Material/ON_Mat_Liquid.mat
414Game/Assets/Personal/Osaki/Scene/ON_ModelTextureTest.unity
414Game/Assets/Personal/Osaki/Script/ON_BottleLiquid.cs
414Game/Assets/Personal/Osaki/Shader/ON_Liquid.shader

修正内容
・満タン時と空の時波を表示しないように
・回転時にも正常に液体が表示されるように
未修正
・空の時液体がちらついて見える

液体シェーダーの修正

---

414Game/Assets/Personal/Osaki/Script/ON_BottleLiquid.cs

ON_Liquid.csのChangeFillingRate()を呼び、引数に0~1の間の充填率を入れる

液体の充填率を外部から変更出来るように更新

---

414Game/Assets/Fade/Materials/UI-Fade-Cutout.mat
414Game/Assets/Personal/Kanase/Prehub/DamageCanvas.prefab
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_BossHP.cs
414Game/Assets/Personal/Kanase/Script/YK_Combo.cs
414Game/Assets/Personal/Kanase/Script/YK_DamageUI.cs
414Game/Assets/Personal/Kanase/Script/YK_Time.cs

Fix DamageUI

---

414Game/Assets/Personal/Kanase/Prehub/DamageCanvas.prefab
414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_CursolEvent.cs
414Game/Assets/Personal/Kanase/Script/YK_DamageUI.cs
414Game/Assets/Personal/Kanase/Script/YK_TakeDamage.cs

Fix DamageCanvas

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_SkillIcon.cs

Fix SkillIcon

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_MoveCursol.cs
414Game/Assets/Personal/Kanase/Script/YK_SkillIcon.cs
414Game/Assets/Personal/Kanase/Script/YK_Time.cs

Fix MoveCursol

---

414Game/Assets/Personal/Ihara/Script/Player/IS_Player.cs
414Game/Assets/Personal/Kanase/Script/YK_CameraOut.cs

Fix Script

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_ScaleDownOrUp.cs
414Game/Assets/Personal/Kanase/Script/YK_Time.cs

Fix Time(Text)

---

414Game/Assets/Personal/Osaki/Script/ON_TextEntry.cs

TextEntry.cs のSetRate(float num)で引数に0~0.5の数字を入れてください

TextEntry関数の修正

---

414Game/Assets/Personal/Kanase/Prehub/YK_Canvas.prefab
414Game/Assets/Personal/Kanase/Script/YK_GameOver.cs
414Game/Assets/Personal/Kanase/Script/YK_Start.cs
414Game/Assets/Script/System/YK_TargetCamera.cs

Fix Camera

---

414Game/Assets/Personal/Kanase/Script/UI/YK_DamageUI.cs
414Game/Assets/Personal/Kanase/Script/UI/YK_Retry.cs

Fix DestroyObject

---

414Game/Assets/Personal/Kanase/Prehub/book.prefab
414Game/Assets/Personal/Kanase/Script/Item/YK_Book.cs
414Game/Assets/Personal/Kanase/Script/Item/YK_Item.cs
414Game/Assets/Personal/Kanase/Script/Item/YK_Item.cs.meta
414Game/Assets/Personal/Kanase/Script/Item/YK_Tonkathi.cs
414Game/Assets/Personal/Kanase/Script/YK_Rule.cs

Create Item Class

---

414Game/Assets/Fungus/Integrations/Playmaker/Fungus-PlayMaker.unitypackage.meta
414Game/Assets/Fungus/Integrations/Spine/Fungus-Spine.unitypackage.meta
414Game/Assets/Personal/Ihara/Script/Player/Walk/IS_PlayerWalk.cs
414Game/Assets/Personal/Kanase/Script/Item/YK_Book.cs

Fix WalkSE
